version: 0.2

phases:
  build:
    commands:
      - echo $ECR_URI
      - echo $CODEBUILD_SOURCE_VERSION
      - REPOSITORY_URI=${ECR_URI}
      - IMAGE_TAG=${CODEBUILD_SOURCE_VERSION}
      - docker buildx build --build-arg ARG_ENV=aws --platform linux/amd64 -f ./docker/php/Dockerfile -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "[{\"name\":\"php\",\"imageUri\":\"${REPOSITORY_URI}:${IMAGE_TAG}\"}]" > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
